// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bPLVSy4qALrK28n1XI_ggpJY-akZAeg',
    appId: '1:1024928259911:web:1190871eb4b0e116a5f662',
    messagingSenderId: '1024928259911',
    projectId: 'first-flutter-app-7f7d0',
    authDomain: 'first-flutter-app-7f7d0.firebaseapp.com',
    storageBucket: 'first-flutter-app-7f7d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLlNcJvgSBPIzAbn7mV0c35xmjBLYldcg',
    appId: '1:1024928259911:android:8ef1e71ccf26dc96a5f662',
    messagingSenderId: '1024928259911',
    projectId: 'first-flutter-app-7f7d0',
    storageBucket: 'first-flutter-app-7f7d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtKynGqCUBccqIh1pBcIwgW2BKRY0xe7U',
    appId: '1:1024928259911:ios:7e1841cc2fa28cc6a5f662',
    messagingSenderId: '1024928259911',
    projectId: 'first-flutter-app-7f7d0',
    storageBucket: 'first-flutter-app-7f7d0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtKynGqCUBccqIh1pBcIwgW2BKRY0xe7U',
    appId: '1:1024928259911:ios:8a5386edc09d6841a5f662',
    messagingSenderId: '1024928259911',
    projectId: 'first-flutter-app-7f7d0',
    storageBucket: 'first-flutter-app-7f7d0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
